DROP TABLE IF EXISTS BOOK;  
CREATE TABLE BOOK (  
id IDENTITY NOT NULL PRIMARY KEY,  
title VARCHAR(100) NOT NULL,  
author VARCHAR(50) NOT NULL ,
isbn VARCHAR(20) NOT NULL,
genre VARCHAR(20),
publish_date DATE NOT NULL
); 


